services:
  mysql:
    image: mysql:latest  
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: exampledb          
      MYSQL_USER: user                   
      MYSQL_PASSWORD: userpassword       
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: userpassword
    ports:
      - "8080:80"

volumes:
  mysql-data:
    driver: local